name: Java CI with Maven, thingsboard

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build docker images
        run: mvn clean install -Ddockerfile.skip=false
      # - name: copy file via ssh key
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     port: ${{ secrets.PORT }}
      #     key: ${{ secrets.KEY }}
      #     source: "."
      #     target: "/home/yalamber"
  # Restart:
  #   name: SSH
  #   needs: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: executing remote ssh commands using ssh key zome
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key: ${{ secrets.KEY }}
  #       port: ${{ secrets.PORT }}
  #       script: |
  #         dpkg -i /home//application/target/thingsboard.deb
  #         service thingsboard start        
         